### ISSUE TITLE
how/where/to get the trust list

### ISSUE THREAD

**Issue by EvergreenHZ** [admin-ch/CovidCertificate-SDK-Kotlin#55]
Hi, I'd like to know how/where to get the trust list. thx.

**Comment by goebelUB** [comment]
This is done up in the Android SDK: https://github.com/admin-ch/CovidCertificate-SDK-Android/blob/main/sdk/src/main/java/ch/admin/bag/covidcertificate/sdk/android/repository/TrustListRepository.kt

**Comment by EvergreenHZ** [comment]
thanks very much. I spend some time to figure out android and java project.
